### ISSUE TITLE
ajax filter still needed?

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-thymeleaf-csrf#2]
Hey @williamsbdev do we still need this ? I thought we had moved away from this recently and if so ... why not kill the dead code ?

https://github.com/toranb/ember-cli-thymeleaf-csrf/blob/master/app/initializers/ajax-prefilter.js#L4

**Comment by williamsbdev** [comment]
@toranb I believe this is still needed. Otherwise, how do we ensure that we are passing back the csrf token on every request?

**Comment by toranb** [comment]
Fair point - just wanted to verify as I thought this was removed recently :)
